# Use the official R base image for the scraper stage
FROM r-base:4.3.1
FROM kyriosskia/metal-world-shiny-app:latest

# Set up the working directory
WORKDIR /app

# Copy your scraping script and any necessary files to the container
COPY . /app/

# Run metalstorm scraper
CMD ["R", "-e", "source('scr/scrape_metalstorm_data.R')"]
