# Use the official R base image
FROM r-base:4.3.1 

# Install system dependencies
RUN apt-get update && apt-get install -y \
  libcurl4-openssl-dev \
  libssl-dev \
  libxml2-dev

# Install R packages using renv
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("rstudio/renv@0.14.0")'

# Set up the working directory
WORKDIR /app

# Copy your app files to the container
COPY . /app

# Install dependencies
RUN R -e 'renv::restore()'




